# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = MCS_gui
DESTDIR = ./debug
CONFIG += debug console
DEFINES += _WINDOWS _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64 QT_DEPRECATED_WARNINGS _UA_STACK_USE_DLL _CRT_SECURE_NO_WARNINGS _CRT_SECURE_NO_DEPRECATE
LIBS += -L"../../../../../../Program Files (x86)/UnifiedAutomation/UaSdkCppBundlePubSubEval/third-party/win64/vs2015/openssl/out32dll.dbg" \
    -L"../../../../../../Program Files (x86)/UnifiedAutomation/UaSdkCppBundlePubSubEval/third-party/win64/vs2015/openssl/out32dll" \
    -L"../../../../../../Program Files (x86)/UnifiedAutomation/UaSdkCppBundlePubSubEval/third-party/win64/vs2015/libxml2/out32dll.dbg" \
    -L"../../../../../../Program Files (x86)/UnifiedAutomation/UaSdkCppBundlePubSubEval/third-party/win64/vs2015/libxml2/out32dll" \
    -L"../../../../../../Program Files (x86)/UnifiedAutomation/UaSdkCppBundlePubSubEval/lib" \
    -L"../../../../../../openssl/lib" \
    -L"../../../../../../Utils/my_sql/mysql-5.7.25-winx64/lib" \
    -L"../../../../../../Utils/postgresql/pgsql/lib" \
    -lshell32 \
    -luastackd \
    -luabasecppd \
    -luapkicppd \
    -luaclientcppd \
    -llibcryptod \
    -lxmlparsercppd \
    -llibxml2d \
    -lcrypt32 \
    -lws2_32 \
    -lrpcrt4
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(MCS_gui.pri)
TRANSLATIONS += qMCS_gui_zh_CN.ts
